version: "3.8"
services:
  # postgres:
  #   container_name: postgres
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: 0bfefac233dcf17d363be29570d
  #     POSTGRES_DB: production
  #     POSTGRES_DEV_USER: dev
  #     POSTGRES_DEV_PASSWORD: 5239dd81cv237a62bcdd95bb4a3
  #     POSTGRES_DEV_DB: development
  #     PGDATA: /var/lib/postgresql/data/
  #   volumes:
  #     - ./database:/var/lib/postgresql/data/
  #     - ./data_exports:/var/lib/postgresql/exports/
  #     - ./init-development-db.sh:/docker-entrypoint-initdb.d/init-development-db.sh
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #     - ./init.sql:/var/lib/data/init.sql
  #   ports:
  #     - "5432:5432"
  #   restart: always

  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "5422:5422"
    volumes:
      - ./web-root:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./dhparam:/etc/ssl/certs
    networks:
      - backend-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email dropgala@gmail.com --agree-tos --no-eff-email --force-renewal -d pgadmin-xyz.dropgala.com

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: dropgala@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123we63zxc49dc0c828ff4
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
    volumes:
      - ./pgadmin:/root/.pgadmin
    restart: unless-stopped
    networks:
      - backend-network

volumes:
  certbot-etc:
  certbot-var:

networks:
  backend-network:
    driver: bridge
