name: Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy database
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # Ip address of the server you wish to ssh into
          key: ${{ secrets.SSH_KEY }} # SSH_KEY is Private key, add the public key to authorized_keys of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          
          script: |
            eval $(ssh-agent -s)
            echo ${{ secrets.SSH_PASSPHRASE }} | SSH_ASKPASS=/usr/bin/cat ssh-add /home/isaac/.ssh/id_rsa_github
            cd dropgala-database
            git pull origin main
            echo 'Successfully Deploy to DigitalOcean'
